language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

script:
  - npm run test

notifications:
  slack: codeforaustralia:1wsYbJH113J8NYM5skthvPuW

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: upload
    skip_cleanup: true
    on:
      repo: CodeforAustralia/cv-staff-app
    bucket: app-playground-storage
    region: ap-southeast-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: app-playground-storage
    key: latest.zip
    bundle_type: zip
    application: cv-staff-app
    deployment_group: admin
    region: ap-southeast-2
    on:
      repo: CodeforAustralia/cv-staff-app

script:
  - zip -r latest * -x node_modules/\*
  - mkdir -p upload
  - mv latest.zip upload/latest.zip
